run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  govet:
    disable-all: true
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - copylocks
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult

issues:
  exclude-use-default: true
